#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# check_credentials:
#     path: /check-credentials
#     controller: App\Controller\AccessController::checkCredentials

# config/routes.yaml
# app_admin:
#     path: /admin/{id}
#     controller: App\Controller\AdminController::index
# config/routes.yaml
home:
    path: /
    controller: App\Controller\HomeController::index

# config/routes.yaml

courses_list:
    path: '/courses/list'
    controller: App\Controller\HomeController::list
    methods: ['GET']
